name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      - run: ls
      - run: ls build

      - name: Upload test results and code coverage Artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*

  # Instrumented はいったん封印する
  #instrumented:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #
  #    - name: set up JDK 17
  #      uses: actions/setup-java@v3
  #      with:
  #        java-version: '17'
  #        distribution: 'temurin'
  #        cache: gradle
  #
  #    - name: Grant execute permission for gradlew
  #      run: chmod +x gradlew
  #
  #    - name: Test with Gradle
  #      run: ./gradlew cAT --stacktrace
  #
  #    - name: Upload test results and code coverage Artifact
  #      uses: actions/upload-artifact@v4
  #      if: success() || failure()
  #      with:
  #        name: cAT-results
  #        path: |
  #          **/build/**/connected

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Inspection
        run: ./gradlew lint

      - run: ls
      - run: ls build

      - name: Upload results Artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: lint-results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - unittest
      - lint
    steps:
      - name: Checkout document repository
        uses: actions/checkout@v3
        with:
          repository: asabon/Documents
          path: work
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: Delete reports
        run: |
          rm -rf work/Calculator/reports

      - name: Download test-result
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./temp/test-results

      - name: Copy test-result to destination
        run: |
          mkdir -p work/Calculator/reports/test-report
          cp -r temp/test-results/app/build/reports/tests/* work/Calculator/reports/test-report/

      - name: Download lint-result
        uses: actions/download-artifact@v4
        with:
          name: lint-results
          path: ./temp/lint-results

      - name: Copy lint-result to destination
        run: |
          mkdir -p work/Calculator/reports/lint-report
          cp -r temp/lint-results/app/build/reports/* work/Calculator/reports/lint-report/

      - name: Commit files to git repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          cd work/Calculator
          git add -A
          if ! git diff --cached --quiet; then
            git commit -a -m "Add changes"
          fi

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: work/Calculator
          repository: asabon/Documents
          ssh: true
