name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      - run: ls
      - run: ls build
      - run: ls build/reports

      - name: Upload test results and code coverage Artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*

#      - name: Checkout document repository
#        uses: actions/checkout@v3
#        with:
#          repository: asabon/Documents
#          path: doc
#          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          persist-credentials: true

#      - name: Copy result to destination
#        run: |
#          rm -rf doc/Calculator/test-reports
#          mkdir -p doc/Calculator/test-reports

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Inspection
        run: ./gradlew lint

      - run: ls
      - run: ls build
      - run: ls build/reports

#      - name: Show results on GitHub
#        uses: yutailang0119/action-android-lint@v1
#        with:
#          xml_path: '**/build/reports/lint-results-*.xml'

      - name: Upload results Artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: lint-results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
